### ISSUE TITLE
CSBI code version 

### ISSUE THREAD

**Issue by HarperHao** [morganstanley/MSML#19]
Thanks for your  great work！

in csbi, when i run evaluation using the example you gave in the readme. but code is error, in train_schrodinger_bridge.py,no evaluation method.
Is this the latest version of the code not uploaded？

**Comment by WayneDW** [comment]
Hi, @HarperHao, thanks for your interest in our work, and sorry for the bug in the code. The main author of the code is not available for the time being and I am here to give you a partial reply. Hope my answer could still solve your concerns. Feel free to let me know if it doesn't work.

I noticed that we can still evaluate the imputation quality in the training by setting "--imputation-eval". I believe this is an alternative method for the evaluation. Here is the example I ran using the Jupyter notebook. 

<img width="990" alt="image" src="https://github.com/morganstanley/MSML/assets/18079879/3484b905-c384-46c5-a12d-c098d107ff28">

**Comment by HarperHao** [comment]
Thank you very much for your reply .  when i try to run SB-FBSDE-Alternate-Imputation-Physio.ipynb.
i'll encounter the error in the image below. i check the error,  the reason is in runner.py  use exist_FID_ckpt(), but in util.py this function is not defined. 
![image](https://github.com/morganstanley/MSML/assets/51149257/ce7026c6-184f-4a4b-95a9-3f1f68ba3ab2)

I checked the github version of the code and really didn't find it. 
so Is the local version of the code correct, but the code uploaded to the github version is wrong？

Looking forward your reply!

**Comment by WayneDW** [comment]
@HarperHao  you can simply set exist_FID_ckpt=0 since that function is mainly for testing in images. The author probably forgot about deleting it when removing the image module.
